### ISSUE TITLE
index not building?

### ISSUE THREAD

**Issue by ekiel** [pirate/ArchiveBox#490]
I just updated the docker container to the latest (Digest:sha256:48a08a1c1e4a2e3480031f25817db57ae398f9720405f5d7495f92a92ced5659) and now when I add links, they seem to process, but the index is no longer rebuilding. I also tried the Django server and my newest archives are no longer showing up.  Here is a snippet of my docker-compose.yml. Currently my archive method is as follows:
```
cat txtfileofurls.txt | docker-compose -f <location of docker-compose.yml> run archivebox add
```
This has been working great for me lately so it seems something has broken, but I'm not sure where to look.
docker-compose.yml:
```
version: '3.7'

services:
    archivebox:
        # build: .
        image: nikisweeting/archivebox:latest
        command: server 0.0.0.0:8000
        stdin_open: true
        tty: true
        ports:
            - 8006:8000
        environment:
            - USE_COLOR=True
            - SHOW_PROGRESS=False
            - SAVE_WARC=False
            - SAVE_PDF=False
            - SAVE_DOM=False
        volumes:
            - /data/archives/general:/data

```
